version: "3.8"
services:
  mysql2:
    image: mysql:8.0
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3308:3306"
    container_name: mysql2
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - liftbro
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.prod
    restart: always
    ports:
      - 8081:8080
    container_name: backend
    depends_on:
      - mysql2
    volumes:
      - .:/backend
    networks:
      - liftbro
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   ports:
  #     - 80:80
  #   container_name: frontend
  #   depends_on:
  #     - backend
  #   networks:
  #     - liftbro

# Networks to be created to facilitate communication between containers
networks:
  liftbro:
    driver: bridge

volumes:
  mysql_data:

  # # UI interface for mysql
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - mysql
  #   env_file:
  #     - .env
  #   ports:
  #     - 9090:80
  #   restart: always
  #   networks:
  #     - backend
