version: "3.8"
services:
  app:
    image: 216448517639.dkr.ecr.ap-southeast-1.amazonaws.com/liftbro:latest
    ports:
      - 8080:8080
    restart: always
    container_name: app
    depends_on:
      - mysql
    networks:
      - backend
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306

  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend

# Networks to be created to facilitate communication between containers
networks:
  backend:
    driver: bridge
# # UI interface for mysql
# phpmyadmin:
#   image: phpmyadmin/phpmyadmin
#   depends_on:
#     - mysql
#   env_file:
#     - .env
#   ports:
#     - 9090:80
#   restart: always
#   networks:
#     - backend
