version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: app
    depends_on:
      - mysql
    volumes:
      - .:/app
    networks:
      - backend
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      # - MYSQL_ROOT_HOST=root
      - MYSQL_USER=liftbro
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=liftbro
    ports:
      - "3307:3306"
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

# Networks to be created to facilitate communication between containers
networks:
  backend:
    driver: bridge

volumes:
  mysql_data:

  # # UI interface for mysql
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - mysql
  #   environment:
  #     - PMA_HOST=mysql
  #     - PMA_USER=root
  #     - PMA_PORT=3306
  #     - PMA_PASSWORD=password
  #   ports:
  #     - 9090:80
  #   restart: always
  #   networks:
  #     - backend
