version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=liftbro
    networks:
      - backend

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=liftbro
    ports:
      - "3307:3306"
    networks:
      - backend
  # # TODO fix the volume
  #     volumes:
  #       - db_data:/var/lib/mysql

  # volumes:
  #   db_data:
  #     external: true

  # # UI interface for mysql
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - mysql
  #   environment:
  #     - PMA_HOST=mysql
  #     - PMA_USER=root
  #     - PMA_PORT=3306
  #     - PMA_PASSWORD=password
  #   ports:
  #     - 9090:80
  #   restart: always
  #   networks:
  #     - backend

# Networks to be created to facilitate communication between containers
networks:
  backend:
    driver: bridge
